### ISSUE TITLE
GAIA sessions not managed properly for multiple users.

### ISSUE THREAD

**Issue by AC-FTW** [blockstack/blockstack-android#100] opened 2018-10-16 19:51 UTC
Stealthy is using an early version of the Blockstack Android SDK and observed an issue where a user's GAIA session remains scoped to the first ID they log in with after logging out and logging in with a second.

This is a significant issue for users with multiple IDs--the session is so persistent, we've found you literally have to uninstall the App and clear the Android phone's Chrome cache (the version of the SDK we're using is proxying all the Blockstack API calls to a webview running Blockstack.js).

Here are the STR (Steps to Reproduce):
1. Have an a Blockstack Android App that writes encrypted files to GAIA and reads them back.
2. Log in with your first.id and write an encrypted file to gaia, e.g. my_encrypted_file.json
3. Log out
4. Log in with your second.id and write the same encrypted file to gaia, my_encrypted_file.json
5. Log out
6. Log back in as first.id and try reading my_encrypte_file.json

This will fail because the file was over-written in step 4 because the GAIA session is still pointing to first.id's gaia from step 1.

**Comment by AC-FTW** [comment] 2018-10-16 19:52
@shreyasthiagaraj Spoke with @jcnelson  about this and am filing it here to document the situation. Not sure if you've addressed this already in Android.

**Comment by friedger** [comment] 2018-10-24 09:40
With the upcoming SDK 0.4.0, I couldn't reproduce the problem.

**Comment by friedger** [comment] 2018-10-24 10:02
The issue in 0.3.0 is that the user can sign in twice without the item in the browser's localstorage for the gaia url been updated.

@AC-FTW If you can force signout, before logging in again that should fix it for the user with 0.3.0.

**Comment by friedger** [comment] 2018-10-24 10:02
I close this issue as it is fixed in 0.4.0

**Closed by friedger** 2018-10-24 10:02 UTC
